version: '3.1'

services:

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  server:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mongo
    environment:
      PORT: 3000
      MONGO_URI: mongodb://root:example@mongo:27017/